openapi: 3.0.3
info:
  title: Attendance Service API
  description: |-
    This is the API documentation of Attendance Service (MOSIP).
  version: 1.0.0

#servers:
#  - url: https://attendance.mosip.uom.lk/api/v1

tags:
  - name: Exams
    description: APIs related to exam attendance
  - name: Lectures
    description: APIs related to lecture attendance
  - name: Users
    description:  APIs related to user authentication/registration

paths:
  /admin/exam-attendance/{examId}:
    get:
      tags:
        - Exams
      summary: Get attendance for an exam
      description: This endpoint will provide a list of enrolled students for an exam with their attendance status.
      operationId: getAttendanceForAnExam
      parameters:
        - name: examId
          in: path
          description: ID of the Exam
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Attendance fetched successfully.
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: "OK"
                  message:
                    type: string
                    example: "Attendance Fetched."
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ExamAttendance'
        '400':
          description: Invalid ID supplied or ID missing
        '404':
          description: Exam ID is not found.
      security:
        - access_token: []

  /admin/login:
    post:
      tags:
        - Users
      summary: Authenticate users
      description: Authenticate the users and receive an access token
      operationId: login
      requestBody:
        description: Login details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestDTO'
        required: true
      responses:
        '200':
          description: Returns the access token after successfully authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenDTO'
        '400':
          description: Invalid inputs/ Missing inputs/ Invalid grant type
        '401':
          description: Invalid credentials
        '404':
          description: Username not found


components:
  schemas:
    ExamAttendance:
      type: object
      properties:
        student_id:
          type: string
          example: 190254R
        present:
          type: boolean
          example: true
        marked_time:
          type: string
          format: date-time
          example: 2023-07-15T11:36:50
          nullable: true

    LoginRequestDTO:
      type: object
      properties:
        grant_type:
          type: string
          description: Grant type for authentication (should always be equal to 'password')
          example: password
          nullable: false
        username:
          type: string
          description: Username (Email) of the user
          example: 'user@gmail.com'
          nullable: false
        password:
          type: string
          description: Password of the user
          example: password
          nullable: false

    AccessTokenDTO:
      type: object
      properties:
        access_token:
          type: string
          example: "eeyabcdefgh"
          description: Access token that can be used to access protected endpoints
        expires_in:
          type: integer
          format: int32
          example: 3600
          description: Token expiry time in seconds

  securitySchemes:
    access_token:
      type: apiKey
      name: Access-Token
      in: header